<?php
/**
 * Support-Ticketing Footer
 *
 * @package		Support-Ticketing
 * @author		Nicholas Valbusa - info@squallstar.it - @squallstar
 * @copyright	Copyright (c) 2011, Squallstar
 * @license		GNU/GPL (General Public License)
 * @link		http://squallstar.it
 *
 */
 
$phrases = array(
	'The best ticketing system ever.',
	'The OMFG bugfixing system!!11',
	'A rapid way to bugfix projects.',
	'Track everything you need to track.',
	'That\'s always you need. Simply.',
	'Yarrr!!',
	'Does it work?',
	'Faster, better, stronger.',
	'Now with a cool interface :)',
	'We got also e-mail notifications.',
	'Powered by Mint',
	'Got a stable and light framework.',
	'Wow it has a bunch of Skype smilies!!',
	'It\'s so tired!!'
);
?>		</div>
		<div class="footer">
		Copyright 2011&copy; Squallstar Studio - <strong><?php echo $phrases[rand(0, count($phrases)-1)]; ?></strong> - Coded by Nicholas Valbusa
		</div>
	</div>
<?php
if (isset($_SESSION['javascript_mailer'])) {
	echo '<script language="javascript" type="text/javascript">'.$_SESSION['javascript_mailer'].'</script>'; 
	unset($_SESSION['javascript_mailer']);
}
?>
</body>
</html>